name: "Build"
on:
  push:
    branches:
      - "master"
      - "develop"
      - "ci/**"

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup MSBuild
        uses: warrenbuckley/Setup-MSBuild@v1

      - name: Setup NuGet
        run: nuget restore Paramdigma.Core.Grasshopper.sln

      - name: Build GH Components
        run: msbuild Paramdigma.Core.Grasshopper.sln /p:Configuration=Release
